# Generated by Django 4.2.7 on 2023-11-18 17:17

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='icon',
            field=models.FileField(upload_to='quiz_icons/', validators=[quiz.models.validate_file_type]),
        ),
    ]
